### ISSUE TITLE
Save analyzer doesn't work

### ISSUE THREAD

**Issue by dabrowawojciech64** [spicyboys/drg-completionist#109] opened 2023-06-29 21:42 UTC

**Comment by NichCodes** [comment] 2023-06-30 22:52
> 

Also it would help if you provided some context as to which part isn't working for you. Knowing your browser and platform would help too.

**Comment by dabrowawojciech64** [comment] 2023-07-01 06:43
Yeah sorry for zero context it was a bit late.
[Here's the save file](https://github.com/spicyboys/drg-completionist/files/11924810/76561198044536461_Player.zip)
After trying to analyze the save I just get an Error Analyzing Save File: with what seems like a blank message.
It seems independent of browser, because I tried both on Firefox 114.0.2, Opera One 100.0.4815.31, Chrome 114.0.5735.199
I made sure to disable adblock everywhere (even when Firefox was a fresh install)

**Comment by rob0rt** [comment] 2023-07-01 21:39
Thanks for the report, I'm currently looking into other parser issues and should have this fixed in a few days!

**Comment by nicosemp** [comment] 2023-07-12 16:56
Is this because of a save file generated by the Windows (XBOX) version of the game, instead of the Steam version?

**Comment by rob0rt** [comment] 2023-07-12 18:55
It should not be, no. The issue mostly stems from just missing types or conditions in the parser

**Comment by nicosemp** [comment] 2023-07-13 08:16
I see. I have a similar issue with my save but it's probably caused by the fact that I started playing through the Xbox Windows app, even though I moved the save over to Steam a couple of years ago.
The error I get in console is `Unhandled property data type NameProperty` at `AnalyzeSaveFile.tsx:218`
Should I open a new issue with my save or just attach it here?

**Comment by dabrowawojciech64** [comment] 2023-07-13 11:38
Yeah, I forgot to mention. Save is exclusively from Steam version.

**Comment by rob0rt** [comment] 2023-07-25 03:40
Resolved as of drg-save-parser version 4.0.0, drg-completionist v5.0.1

**Closed by rob0rt** 2023-07-25 03:40 UTC
Labels: bug
